correct envs

diff --git a/envs/REPLAY b/envs/REPLAY
--- a/envs/REPLAY
+++ b/envs/REPLAY
@@ -1,1 +1,6 @@
-export ASAN_OPTIONS="detect_odr_violation=0:abort_on_error=1:symbolize=1:detect_leaks=0"
+export ASAN_OPTIONS=detect_odr_violation=0:abort_on_error=1:symbolize=1:detect_leaks=0:allocator_may_return_null=1
+hash llvm-symbolizer &> /dev/null
+if [[ $? -ne 0 ]]; then
+    echo "llvm-symoblizer NOT FOUND"
+fi
+export ASAN_SYMBOLIZER_PATH=$(realpath $(which llvm-symbolizer))
